services:
  mysql:
    image: mysql:8.0.41
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=traveldb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword